### Get all movies
GET http://localhost:3000/movies

### Get movie by id
GET http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Get all movies by genre
GET http://localhost:3000/movies?genre=action

### Create a movie
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "The Dark Knight",
  "year": 2008,
  "director": "Christopher Nolan",
  "duration": 152,
  "poster": "https://i.ebayimg.com/images/g/yokAAOSw8w1YARbm/s-l1200.jpg",
  "genre": ["Action", "Crime", "Drama"],
  "rate": 9.0
}

### Update a movie
PATCH http://localhost:3000/movies/241bf55d-b649-4109-af7c-0e6890ded3fc
Content-Type: application/json

{
  "year": 1994
}