### Get all movies
GET http://localhost:3000/movies

### Get movie by id
GET http://localhost:3000/movies/aa6d2254-875d-11ef-b10a-1101d116f89c

### Get all movies by genre
GET http://localhost:3000/movies?genre=action

### Create a movie
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "The Dark Knight",
  "year": 2008,
  "director": "Christopher Nolan",
  "duration": 152,
  "poster": "https://i.ebayimg.com/images/g/yokAAOSw8w1YARbm/s-l1200.jpg",
  "genre": ["Action", "Crime", "Drama"],
  "rate": 9.0
}

### Update a movie
PATCH http://localhost:3000/movies/4e7c5f64-87f8-11ef-b10a-1101d116f89c
Content-Type: application/json

{
  "duration": 420,
  "director": "Zack Snyder"
}

### Delete a movie
DELETE http://localhost:3000/movies/83c83e5a-87a2-11ef-b10a-1101d116f89c
Content-Type: application/json

### Update a movie
PATCH http://localhost:3000/movies/83c83f5e-87a2-11ef-b10a-1101d116f89c
Content-Type: application/json

{
  "year": 2000
}